### PR TITLE
Automatically push Docker image to Docker Hub

### PR DESCRIPTION
**Pull request by ErikSchierboom**
The [v3 development environment](https://github.com/exercism/development-environment/) uses Docker images from Docker Hub for all the tooling.
This allows for easy testing of the various tooling components (analyzers/representer/test-runners).

This PR adds a GitHub Actions workflow to automatically build and push a new Docker image whenever something is merged to master.

See https://github.com/exercism/v3/issues/2727

### CODE REVIEW

**Comment by verdammelt** [comment]
@ErikSchierboom I think we already have this docker hub action for this project. https://github.com/exercism/common-lisp-analyzer/blob/master/.github/workflow/dockerhub.yml

**Comment by ErikSchierboom** [comment]
@verdammelt At first I was like: damn, was there a bug in my script? But then I noticed that the existing file is in the wrong folder: `workflow` instead of the correct `workflows`. :)

The version in this PR also has the advantage that it is repository agnostic (the repo name is parameterized), although admittedly that's a rather academic advantage as it is unlikely that we ever change this repo name.

**Comment by verdammelt** [comment]
`workflow` vs `workflows` - UGH.

I'd like to add removing the wrong one to this PR - but then will happily merge it. (should be able to do that later today...)

**Comment by ErikSchierboom** [comment]
Great!

**Review by verdammelt — APPROVED** [review]

**Pull request merged**
