### PR TITLE
create a "complete" but still "null operation" implementation.

### PR DESCRIPTION
**Pull request by verdammelt**

### CODE REVIEW

**Review by TheLostLambda — COMMENTED** [review]
Not too much to say here, it's looking great! I pulled it and built it with Docker without any issues. The package structure is quite clean and makes dependencies very easy to keep track of.

With that being said, I do have one thing we should probably figure out before merging: which JSON library to use. There are far too many for Lisp and I think I've used a different one in the test-runner than you have here. While we could use two different ones, it might be good to standardize on one.

I've used `st-json` in the test-runner and quite like it, but I'm open to hearing why you've chosen `yason` as well :)

**Comment by verdammelt** [comment]
This is basically the code from the representer with `s/representer/analyzer` applied to it :)

I'll try to remember why i didn't go with `st-json` I remember using it when i started on the representer - but then switched to `yason`. I know there was a *reason*. Just can't necessarily remember if it was a *good reason*!

**Comment by verdammelt** [comment]
@TheLostLambda ah I think I remember why I switched from `st-json`. I wanted to keep the data as 'native' CL types like assoc lists instead of `st-json:jso` types. `yason` let me just do the transformation to JSON right at the very edge of the system.

It also let me read in JSON to an alist easily - which helped me when I wanted to write some end-to-end tests...


(The first part *is* how you are using `st-json`... so if we do switch to `st-json` I'd just write a wrapper to it to read/write alists...)

**Comment by TheLostLambda** [comment]
Ah, okay, that makes sense! I think it's probably fine to stick with `yason` then? If we do want to pull out some common code that involves JSON work at some point, we could readdress this, but it's probably alright to have both for the time being.

I'll look more into `st-json` vs `yason` in the test-runner as well. I think I ended up with `st-json` because it seemed to handle the special JSON null, undefined, and false values well, but those don't really come up all that often in the test runner anyways.

This looks like a great start!

**Review by TheLostLambda — APPROVED** [review]

**Pull request merged**
